apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "deployer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "deployer.name" . }}
    helm.sh/chart: {{ include "deployer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deployer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deployer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: ssh-key-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["/bin/deployer", "serve"]
          env:
            - name: VERSIONS_URL
              value: "{{ .Values.global.versionsRepoUrl }}"
            - name: VERSIONS_CHECKOUT_PATH
              value: "/data"
            - name: API_PORT
              value: "80"
            - name: SSH_PRIVATE_KEY
              value: /ssh-keys/id_rsa
            - name: SSH_PUBLIC_KEY
              value: /ssh-keys/id_rsa.pub
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/ssh-keys"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
