versions_url: "./versions.git"
versions_checkout_path: %%versions_checkout_path%%
api_port: %%api_port%%
deployers:
  dev:
    type: Mock
  prod:
    type: Mock
transitions:
  prod:
    source: dev
    target: prod
    preconditions:
      - SourceClean
  dev:
    source: latest
    target: dev
deployer_url: "http://localhost:%%deployer_port%%"
transitioner_url: "http://localhost:%%transitioner_port%%"
