# Default values for deployer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

global:
  versionsRepoUrl: git://foo
  image:
    repository: flodiebold/cautious-tribble
    tag: latest
    pullPolicy: IfNotPresent
